version: '3.7'

services:
  mysql:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_DATABASE: rh
      MYSQL_USER: fabio
      MYSQL_PASSWORD: fabio
      MYSQL_ROOT_PASSWORD: fabio
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  rh-domain:
    build:
      context: ./rh-domain
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - mysql

  rh-web:
    build:
      context: ./rh-web
      dockerfile: Dockerfile
    ports:
      - "8081:8080"
    depends_on:
      - mysql
      - rh-domain

  rh-persistencia:
    build:
      context: ./rh-persistencia
      dockerfile: Dockerfile
    ports:
      - "8082:8080"
    depends_on:
      - mysql
      - rh-domain

volumes:
  mysql_data:
